const
  emImg = 'Error loading image';
  emWnd = 'Error opening window';
  emIni = 'Error during initialization';
  emSrf = 'Error Initializing surface';
  emCtx = 'Error initializing context';
  emIgl = 'Error initializing GL';
  emNoF = 'Error opening file ';
  emCrF = 'Error creating file ';
  emFiC = 'File is corrupted ';

  msgFCr = 'Creating new file';

  xmlCreateE = 'Error creating XML object ';
